"use strict";(self.webpackChunkobol_docs=self.webpackChunkobol_docs||[]).push([[2570],{15680:(e,t,o)=>{o.d(t,{xA:()=>c,yg:()=>h});var a=o(96540);function r(e,t,o){return t in e?Object.defineProperty(e,t,{value:o,enumerable:!0,configurable:!0,writable:!0}):e[t]=o,e}function n(e,t){var o=Object.keys(e);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);t&&(a=a.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),o.push.apply(o,a)}return o}function i(e){for(var t=1;t<arguments.length;t++){var o=null!=arguments[t]?arguments[t]:{};t%2?n(Object(o),!0).forEach((function(t){r(e,t,o[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(o)):n(Object(o)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(o,t))}))}return e}function s(e,t){if(null==e)return{};var o,a,r=function(e,t){if(null==e)return{};var o,a,r={},n=Object.keys(e);for(a=0;a<n.length;a++)o=n[a],t.indexOf(o)>=0||(r[o]=e[o]);return r}(e,t);if(Object.getOwnPropertySymbols){var n=Object.getOwnPropertySymbols(e);for(a=0;a<n.length;a++)o=n[a],t.indexOf(o)>=0||Object.prototype.propertyIsEnumerable.call(e,o)&&(r[o]=e[o])}return r}var l=a.createContext({}),d=function(e){var t=a.useContext(l),o=t;return e&&(o="function"==typeof e?e(t):i(i({},t),e)),o},c=function(e){var t=d(e.components);return a.createElement(l.Provider,{value:t},e.children)},u="mdxType",g={inlineCode:"code",wrapper:function(e){var t=e.children;return a.createElement(a.Fragment,{},t)}},y=a.forwardRef((function(e,t){var o=e.components,r=e.mdxType,n=e.originalType,l=e.parentName,c=s(e,["components","mdxType","originalType","parentName"]),u=d(o),y=r,h=u["".concat(l,".").concat(y)]||u[y]||g[y]||n;return o?a.createElement(h,i(i({ref:t},c),{},{components:o})):a.createElement(h,i({ref:t},c))}));function h(e,t){var o=arguments,r=t&&t.mdxType;if("string"==typeof e||r){var n=o.length,i=new Array(n);i[0]=y;var s={};for(var l in t)hasOwnProperty.call(t,l)&&(s[l]=t[l]);s.originalType=e,s[u]="string"==typeof e?e:r,i[1]=s;for(var d=2;d<n;d++)i[d]=o[d];return a.createElement.apply(null,i)}return a.createElement.apply(null,o)}y.displayName="MDXCreateElement"},84629:(e,t,o)=>{o.r(t),o.d(t,{assets:()=>l,contentTitle:()=>i,default:()=>g,frontMatter:()=>n,metadata:()=>s,toc:()=>d});var a=o(58168),r=(o(96540),o(15680));const n={sidebar_position:2,description:"Errors & Resolutions"},i="Errors & Resolutions",s={unversionedId:"faq/errors",id:"faq/errors",title:"Errors & Resolutions",description:"Errors & Resolutions",source:"@site/docs/faq/errors.mdx",sourceDirName:"faq",slug:"/faq/errors",permalink:"/docs/next/faq/errors",draft:!1,editUrl:"https://github.com/ObolNetwork/obol-docs/edit/main/docs/faq/errors.mdx",tags:[],version:"current",sidebarPosition:2,frontMatter:{sidebar_position:2,description:"Errors & Resolutions"},sidebar:"tutorialSidebar",previous:{title:"Frequently asked questions",permalink:"/docs/next/faq/general"},next:{title:"Centralization risks and mitigation",permalink:"/docs/next/faq/risks"}},l={},d=[],c={toc:d},u="wrapper";function g(e){let{components:t,...o}=e;return(0,r.yg)(u,(0,a.A)({},c,o,{components:t,mdxType:"MDXLayout"}),(0,r.yg)("h1",{id:"errors--resolutions"},"Errors & Resolutions"),(0,r.yg)("p",null,"All operators should try to restart their nodes and should check if they are on the latest stable version before attempting anything other configuration change as we are still in beta and frequently releasing fixes. You can restart and update with the following commands:"),(0,r.yg)("pre",null,(0,r.yg)("code",{parentName:"pre",className:"language-shell"},"docker compose down\ngit pull\ndocker compose up\n")),(0,r.yg)("p",null,"You can check your logs using"),(0,r.yg)("pre",null,(0,r.yg)("code",{parentName:"pre",className:"language-shell"},"docker compose logs\n")),(0,r.yg)("details",{open:!0,className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h2",{id:"enrs-keys"},"ENRs & Keys")),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"what-is-an-enr"},"What is an ENR?")),"An ENR is shorthand for an ",(0,r.yg)("a",{href:"https://eips.ethereum.org/EIPS/eip-778"},"Ethereum Node Record"),". It is a way to represent a node on a public network, with a reliable mechanism to update its information.",(0,r.yg)("br",null),(0,r.yg)("br",null),"At Obol we use ENRs to identify Charon nodes to one another such that they can form clusters with the right Charon nodes and not impostors. ENRs have private keys they use to sign updates to the ",(0,r.yg)("a",{href:"https://enr-viewer.com/"},"data contained")," in their ENR. This private key is by default found at ",(0,r.yg)("code",null,".charon/charon-enr-private-key"),", and should be kept secure, and not checked into version control.",(0,r.yg)("br",null),(0,r.yg)("br",null),"An ENR looks something like this: ",(0,r.yg)("pre",null,(0,r.yg)("code",null,"enr:-JG4QAgAOXjGFcTIkXBO30aUMzg2YSo1CYV0OH8Sf2s7zA2kFjVC9ZQ_jZZItdE8gA-tUXW-rWGDqEcoQkeJ98Pw7GaGAYFI7eoegmlkgnY0gmlwhCKNyGGJc2VjcDI1NmsxoQI6SQlzw3WGZ_VxFHLhawQFhCK8Aw7Z0zq8IABksuJEJIN0Y3CCPoODdWRwgj6E"))),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"generate-enr-again"},"How do I get my ENR if I want to generate it again?")),(0,r.yg)("ul",null,(0,r.yg)("li",null,(0,r.yg)("code",null,"cd")," to the directory where your private keys are located (ex: ",(0,r.yg)("code",null,"cd /path/to/charon/enr/private/key"),")"),(0,r.yg)("li",null,"Run ",(0,r.yg)("code",null,'docker run --rm -v "$(pwd):/opt/charon" obolnetwork/charon:latest enr'),". This prints the ENR on your screen. "),(0,r.yg)("li",null,"Please note that this ENR is not the same as the one generated when you created it for the first time. This is because the process of generating ENRs includes the current timestamp."))),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"lost-enr-private-key"}," What do I do if lose my ",(0,r.yg)("code",null,"charon-enr-private-key"),"? ")),(0,r.yg)("ul",null,(0,r.yg)("li",null," For now, ENR rotation/replacement is not supported, it will be supported in a future release. "),(0,r.yg)("li",null," Therefore, it's advised to always keep a backup of your"," "," ",(0,r.yg)("code",null,"charon-enr-private-key")," in a secure location (ex: cloud storage, USB Flash drive, etc.). "))),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"lost-keys"},"I can't find the keys anywhere")),(0,r.yg)("ul",null,(0,r.yg)("li",null,"The ",(0,r.yg)("code",null,"charon-enr-private-key")," is generated inside a hidden folder ",(0,r.yg)("code",null,".charon"),". "),(0,r.yg)("li",null,"To view it, run ",(0,r.yg)("code",null,"ls -al")," in your terminal. "),(0,r.yg)("li",null,"You can then copy the key to your ",(0,r.yg)("code",null,"~/Downloads")," folder for easy access by running ",(0,r.yg)("code",null,"cp .charon/charon-enr-private-key ~/Downloads"),". This step maybe a bit different for Windows. "),(0,r.yg)("li",null,"Else, if you are on macOS, press ",(0,r.yg)("code",null,"Cmd + Shift + .")," to view the ",(0,r.yg)("code",null,".charon")," folder in the Finder application. ")))),(0,r.yg)("details",{open:!0,className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h2",{id:"lighthouse"},"Lighthouse")),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"downloading-historical-blocks"},"Downloading historical blocks"))," This means that Lighthouse is still syncing which will throw a lot of errors down the line. Wait for the sync before moving further."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"failed-to-request-attester-duties"},(0,r.yg)("code",null,"Failed to request attester duties")," error"))," Indicates there is something wrong with your Lighthouse beacon node. This might be because the request buffer is full as your node is never starting consensus since it never gets the duties."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"discovery-search-timeout"},(0,r.yg)("code",null,"Not enough time for a discovery seach")," error"))," This could be linked to a internet connection being too slow or relying on a slow third-party service such as Infura.")),(0,r.yg)("details",{open:!0,className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h2",{id:"beacon-node"},"Beacon Node")),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"error-communicating-with-beacon-node-api"},(0,r.yg)("code",null,"Error communicating with Beacon Node API")," & ",(0,r.yg)("code",null,"Error while connecting to beacon node event stream")))," This is likely due to Lighthouse not done syncing, wait and try again once synced. Can also be linked to Teku keystore issue."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"clock-sync-issues"},"Clock sync issues"))," Either your clock server time is off, or you are talking to a remote beacon client that is super slow (this is why we advise against using services like Infura)."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"beacon-node-API-flaky"},"My beacon node API is flaky with lots of errors and timeouts")),"A good quality beacon node API is critical to validator performance. It is always advised to run your own beacon node to ensure low latencies to boost validator performance.",(0,r.yg)("br",null),(0,r.yg)("br",null),"Using 3rd party services like Infura's beacon node API has significant disadvantages since the quality is often low. Requests often return 500s or timeout (Charon times out after 2s). This results in lots of warnings and errors and failed duties. Running a local beacon node is always preferred. We are not yet considering increasing the 2s timeout since that can have knock-on effects.")),(0,r.yg)("details",{open:!0,className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h2",{id:"charon"},"Charon")),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"attester-failed-in-consensus-component-error"},(0,r.yg)("code",null,"Attester failed in consensus component")," error"))," The required number of operators defined in your cluster-lock file is probably not online to sign successfully. Make sure all operators are running the latest version of Charon. To check if some peers are not online: ",(0,r.yg)("code",null," docker logs charon-distributed-validator-node-charon-1 2>&1 | grep 'absent' ")),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"load-private-key-error"},(0,r.yg)("code",null,"Load private key")," error"))," Make sure you have successfully run a DKG before running the node. The key should be created and placed in the right directory during the ceremony. Also, make sure you are working in the right directory: ",(0,r.yg)("code",null,"charon-distributed-validator-node"),"."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"failed-to-confirm-node-connection-error"},(0,r.yg)("code",null,"Failed to confirm node connection")," error"))," Wait for Teku & Lighthouse sync to be complete."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"reserve-relay-circuit-error"},(0,r.yg)("code",null,"Reserve relay circuit: reservation failed")," error")),(0,r.yg)("code",null,"RESERVATION_REFUSED"),' is returned by the libp2p relay when some maximum limit has been reached. This is most often due to "maximum reservations per IP/peer". This is when your Charon node is restarting or in some error loop and constantly attempting to create new relay reservations reaching the maximum.',(0,r.yg)("br",null),(0,r.yg)("br",null),'To fix this error, stop your Charon node for 30mins before restarting it. This should allow the relay enough time to reset your IP/peer limits and should then allow new reservations. This could also be due to the relay being overloaded in general, so reaching a server wide "maximum connections" limit. This is an issue with relay scalability and we are working in a long term fix for this.'),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"opening-relay-circuit-error"},(0,r.yg)("code",null,"Error opening relay circuit: NO_RESERVATION")," error")),(0,r.yg)("code",null,"Error opening relay circuit NO_RESERVATION (204)")," indicates the peer isn't connected to the relay, so the the Charon client cannot connect to the peer via the relay. That might be because the peer is offline or the peer is configured to connect to a different relay.",(0,r.yg)("br",null),(0,r.yg)("br",null),"To fix this error, ensure the peer is online and configured with the exact same ",(0,r.yg)("code",null,"--p2p-relays")," flag."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"duty-data-from-beacon-node-error"},(0,r.yg)("code",null,"Couldn't fetch duty data from the beacon node")," error")),(0,r.yg)("code",null,"msgFetcher")," indicates a duty failed in the fetcher component when it failed to fetch the required data from the beacon node API. This indicates a problem with the upstream beacon node."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"aggregate-attestation-error"},(0,r.yg)("code",null,"Couldn't aggregate attestation due to failed attester duty")," error")),(0,r.yg)("code",null,"msgFetcherAggregatorNoAttData")," indicates an attestation aggregation duty failed in the fetcher component since it couldn't fetch the prerequisite attestation data. This indicates the associated attestation duty failed to obtain a cluster agreed upon value."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"aggregate-attestation-insufficient-partial-v2-committee-error"},(0,r.yg)("code",null,"Couldn't aggregate attestation due to insufficient partial v2 committee subscriptions")," error")),(0,r.yg)("code",null,"msgFetcherAggregatorZeroPrepares")," indicates an attestation aggregation duty failed in the fetcher component since it couldn't fetch the prerequisite aggregated v2 committee subscription. This indicates the associated prepare aggregation duty failed due to no partial v2 committee subscription submitted by the cluster validator clients."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"aggregate-attestation-failed-prepare-aggregator-duty-error"},(0,r.yg)("code",null,"Couldn't aggregate attestation due to failed prepare aggregator duty")," error")),(0,r.yg)("code",null,"msgFetcherAggregatorFailedPrepare")," indicates an attestation aggregation duty failed in the fetcher component since it couldn't fetch the prerequisite aggregated v2 committee subscription. This indicates the associated prepare aggregation duty failed."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"insufficient-partial-randao-signatures-error"},(0,r.yg)("code",null,"Couldn't propose block due to insufficient partial randao signatures")," error")),(0,r.yg)("code",null,"msgFetcherProposerFewRandaos")," indicates a block proposer duty failed in the fetcher component since it couldn't fetch the prerequisite aggregated RANDAO. This indicates the associated randao duty failed due to insufficient partial randao signatures submitted by the cluster validator clients."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"zero-partial-randao-signatures-error"},(0,r.yg)("code",null,"Couldn't propose block due to zero partial randao signatures")," error")),(0,r.yg)("code",null,"msgFetcherProposerZeroRandaos")," indicates a block proposer duty failed in the fetcher component since it couldn't fetch the prerequisite aggregated RANDAO. This indicates the associated randao duty failed due to no partial randao signatures submitted by the cluster validator clients."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"failed-randao-duty-error"},(0,r.yg)("code",null,"Couldn't propose block due to failed randao duty")," error")),(0,r.yg)("code",null,"msgFetcherProposerZeroRandaos")," indicates a block proposer duty failed in the fetcher component since it couldn't fetch the prerequisite aggregated RANDAO. This indicates the associated randao duty failed."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"consensus-algorithm-not-complete-error"},(0,r.yg)("code",null,"Consensus algorithm didn't complete")," error")),(0,r.yg)("code",null,"msgConsensus")," indicates a duty failed in consensus component. This could indicate that insufficient honest peers participated in consensus or p2p network connection problems."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"signed-duty-not-submitted-error"},(0,r.yg)("code",null,"Signed duty not submitted by local validator client")," error")),(0,r.yg)("code",null,"msgValidatorAPI")," indicates that partial signature were never submitted by the local validator client. This could indicate that the local validator client is offline, or has connection problems with Charon, or has some other problem. See validator client logs for more details."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"partial-signature-exchange-error"},(0,r.yg)("code",null,"Bug: partial signature database didn't trigger partial signature exchange")," error")),(0,r.yg)("code",null,"msgParSigDBInternal")," indicates a bug in the partial signature database as it is unexpected."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"no-partial-signature-received-error"},(0,r.yg)("code",null,"No partial signatures received from peers")," error")),(0,r.yg)("code",null,"msgParSigEx")," indicates that no partial signature for the duty was received from any peer. This indicates all peers are offline or p2p network connection problems."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"insufficient-partial-signatures-received-error"},(0,r.yg)("code",null,"Insufficient partial signatures received, minimum required threshold not reached")," error")),(0,r.yg)("code",null,"msgParSigDBThreshold")," indicates that insufficient partial signatures for the duty was received from peers. This indicates problems with peers or p2p network connection problems."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"inconsistent-signed-data-error"},(0,r.yg)("code",null,"Bug: threshold aggregation of partial signatures failed due to inconsistent signed data")," error")),(0,r.yg)("code",null,"msgSigAgg")," indicates that BLS threshold aggregation of sufficient partial signatures failed. This indicates inconsistent signed data. This indicates a bug in Charon as it is unexpected."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"private-key-lock-error"},(0,r.yg)("code",null,"Existing private key lock file found, another charon instance may be running on your machine")," error")),"When you turn on the ",(0,r.yg)("code",null,"--private-key-file-lock")," option in Charon, it checks for a special file called the private key lock file. This file has the same name as the ENR private key file but with a ",(0,r.yg)("code",null,".lock")," extension. If the private key lock file exists and is not older than 5 seconds, Charon won't run. It doesn't allow running multiple Charon instances with the same ENR private key. If the private key lock file has a timestamp older than 5 seconds, Charon will replace it and continue with its work. If you're sure that no other Charon instances are running, you can delete the private key lock file."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"mismatching-validator-client-key"},(0,r.yg)("code",null,"Validator api 5xx response: mismatching validator client key share index, Mth key share submitted to Nth charon peer")," error")),"The issue revolves around an invalid setup or deployment, where keyshares are not tied to the ENR private key. There appears to be a mix-up during deployment, leading to a mismatching validator client key share index.",(0,r.yg)("ul",null,"For example:"),(0,r.yg)("ul",null,"Imagine node N is Alice, and node M is Bob, the error would read:",(0,r.yg)("code",null,"mismatching validator client key share index, Bob's key share submitted to Alice's charon node"),"."),(0,r.yg)("ul",null,"Bob's private key share(s) are imported to a VC that is connected to Alice's Charon node. This is a invalid setup/deployment. Alice's Charon node should only be connected to Alice's VC."),"Check the keyshare of each node inside cluster-lock.json and see that matches with the key inside ",(0,r.yg)("code",null,"node(num)/validator_keys/keystore-0.json"),".")),(0,r.yg)("details",{open:!0,className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h2",{id:"teku"},"Teku")),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"teku-keystore-file-error"},"Teku ",(0,r.yg)("code",null,"keystore file")," error "))," Teku sometimes logs an error which looks like ",(0,r.yg)("code",null,"Keystore file /opt/charon/validator_keys/keystore-0.json.lock already in use"),". This can be solved by deleting the file(s) ending with ",(0,r.yg)("code",null,".lock")," in the folder ",(0,r.yg)("code",null,".charon/validator_keys"),". It is caused by an unsafe shut down of Teku (usually by double pressing ",(0,r.yg)("code",null,"Ctrl+C")," to shutdown containers faster).")),(0,r.yg)("details",{open:!0,className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h2",{id:"grafana"}," Grafana ")),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"how-to-fix-grafana-dashboard"}," How to fix the Grafana dashboard? "))," Sometimes, Grafana dashboard doesn't load any data first time around. You can solve this by following the steps below: ",(0,r.yg)("ul",null,(0,r.yg)("li",null,"Click the Wheel Icon > Datasources."),(0,r.yg)("li",null,"Click prometheus."),(0,r.yg)("li",null,'Change the "Access" field from ',(0,r.yg)("code",null,"Server (default)")," to ",(0,r.yg)("code",null,"Browser"),'. Press "Save & Test". It should fail. '),(0,r.yg)("li",null,'Change the "Access" field back to ',(0,r.yg)("code",null,"Server (default)"),' and press "Save & Test". You should be presented with a green success icon saying "Data source is working" and you can return to the dashboard page. '))),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"no-data-validator-info-panel"},(0,r.yg)("code",null,"N/A")," & ",(0,r.yg)("code",null,"No data")," in validator info panel"))," Can be linked to a Teku keystore issue.")),(0,r.yg)("details",{open:!0,className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h2",{id:"prometheus"},"Prometheus")),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"unauthorized-invalid-token-error"},(0,r.yg)("code",null,"Unauthorized: authentication error: invalid token")))," You can ignore this error unless you have been contacted by the Obol Team with monitoring credentials. In that case, follow ",(0,r.yg)("a",{href:"../advanced/monitoring"},"Getting Started Monitoring your Node")," in our advanced guides. It does not affect cluster performance or prevent the cluster from running.")),(0,r.yg)("details",{open:!0,className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h2",{id:"docker"}," Docker ")),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"docker-permission-denied-error"}," How to fix ",(0,r.yg)("code",null,"permission denied")," errors? "))," Permission denied errors can come up in a variety of manners, particularly on Linux and WSL for Windows systems. In the interest of security, the charon docker image runs as a non-root user, and this user often does not have the permissions to write in the directory you have checked out the code to. This can be generally be fixed with some of the following: ",(0,r.yg)("ul",null,(0,r.yg)("li",null,"Running docker commands with ",(0,r.yg)("code",null,"sudo"),", if you haven't ",(0,r.yg)("a",{href:"https://docs.docker.com/engine/install/linux-postinstall/"},"setup docker to be run as a non-root user"),". "),(0,r.yg)("li",null,"Changing the permissions of the ",(0,r.yg)("code",null,".charon")," folder with the commands: "),(0,r.yg)("ul",null,(0,r.yg)("li",null,(0,r.yg)("code",null,"mkdir .charon")," (if it doesn't already exist);"),(0,r.yg)("li",null,(0,r.yg)("code",null,"sudo chmod -R 666 .charon"),".")))),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"running-docker-compose-up-error"}," I see a lot of errors after running ",(0,r.yg)("code",null,"docker compose up")))," It's because both Geth and Lighthouse start syncing and so there's connectivity issues among the containers. Simply let the containers run for a while. You won't observe frequent errors when Geth finishes syncing. You can also add a second beacon node endpoint for something like Infura by adding a comma separated API URL to the end of ",(0,r.yg)("code",null,"CHARON_BEACON_NODE_ENDPOINTS")," in the docker-compose.yml."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"loki-plugin-not-found-error"}," How do I fix the ",(0,r.yg)("code",null,'plugin "loki" not found')," error?"))," If you get the following error when calling ",(0,r.yg)("code",null,"docker compose up"),":",(0,r.yg)("br",null),(0,r.yg)("code",null,'Error response from daemon: error looking up logging plugin loki: plugin "loki" not found'),".",(0,r.yg)("br",null),"Then it probably means that the Loki docker driver isn't installed. In that case, run the following command to install loki:",(0,r.yg)("br",null),(0,r.yg)("code",null,"docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions"),".")),(0,r.yg)("details",{open:!0,className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h2",{id:"Relay"},"Relay")),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"resolve-ip-or-p2p-external-host-flag-error"},(0,r.yg)("code",null," Resolve IP of p2p external host flag: lookup replace.with.public.ip.or.hostname: no such host ")," "," error"))," Replace ",(0,r.yg)("code",null,"replace.with.public.ip.or.hostname")," in the relay/docker-compose.yml with your real public IP or DNS hostname."),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"timeout-resolving-bootnode-enr"},(0,r.yg)("code",null," Timeout resolving bootnode ENR: context deadline exceeded ")," "," error"))," The relay you are trying to connect to your peers via is offline or unreachable.")),(0,r.yg)("details",{open:!0,className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h2",{id:"Lodestar"},"Lodestar")),(0,r.yg)("details",{className:"details"},(0,r.yg)("summary",null,(0,r.yg)("h4",{id:"Potential-next-epoch-attester-duties-reorg-slot-821-error"},(0,r.yg)("code",null," warn: Potential next epoch attester duties reorg")," "," error"))," Lodestar logs these warnings because Charon is not able to return proper ",(0,r.yg)("code",null,"dependent_root")," value in ",(0,r.yg)("code",null,"getAttesterDuties")," API response whenever Lodestar calls this API. This is because Charon uses ",(0,r.yg)("code",null,"go-eth2-client")," for all the beacon API calls and it doesn't provide ",(0,r.yg)("code",null,"dependent_root")," value in responses. We have reported this to them ",(0,r.yg)("a",{href:"https://github.com/attestantio/go-eth2-client/issues/35"},"here"),".")))}g.isMDXComponent=!0}}]);